name: 🤖 AI Integration Issue
description: Report an issue with Anthropic AI integration in Claude Ecosystem Standard
title: "[AI] "
labels: ["anthropic-ai", "ai-integration", "medium-priority"]
assignees:
  - anthropic-integration-lead

body:
  - type: markdown
    attributes:
      value: |
        ## 🤖 AI Integration Issue Report
        
        Help us improve the Anthropic AI integration by reporting issues with AI features, API calls, or SDK usage.

  - type: input
    id: version
    attributes:
      label: CES Version
      description: What version of Claude Ecosystem Standard are you using?
      placeholder: v2.7.0
    validations:
      required: true

  - type: input
    id: anthropic-sdk-version
    attributes:
      label: Anthropic SDK Version
      description: What version of @anthropic-ai/sdk is being used?
      placeholder: ^0.57.0
    validations:
      required: true

  - type: dropdown
    id: ai-component
    attributes:
      label: AI Component
      description: Which AI component is experiencing issues?
      options:
        - Anthropic CLI Commands
        - AI Session Manager
        - SDK Configuration
        - API Key Management
        - Model Selection
        - Streaming Responses
        - Conversation Management
        - Usage Analytics
        - Error Handling
        - Token Counting
        - Rate Limiting
        - Code Analysis
        - Code Generation
        - Interactive Chat
        - Other
    validations:
      required: true

  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type
      description: What type of AI integration issue is this?
      options:
        - API Connection Failed
        - Authentication Error
        - Invalid Response Format
        - Streaming Issues
        - Token Limit Exceeded
        - Rate Limiting
        - Model Not Available
        - Configuration Error
        - SDK Compatibility
        - Performance Issue
        - Feature Not Working
        - Unexpected Behavior
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Issue Description
      description: Detailed description of the AI integration issue
      placeholder: |
        Describe the AI integration issue:
        - What AI feature were you using?
        - What went wrong?
        - What error messages did you see?
        - When did this start happening?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: How to reproduce this AI integration issue
      placeholder: |
        1. Configure AI with...
        2. Run command: npm run dev -- ai ask "..."
        3. Observe error...
        4. Check logs...
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected AI Behavior
      description: What did you expect the AI integration to do?
      placeholder: |
        - Expected AI response
        - Expected command behavior
        - Expected error handling
        - Expected performance
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual AI Behavior
      description: What actually happened with the AI integration?
      placeholder: |
        - Actual AI response (if any)
        - Error messages received
        - Unexpected behavior observed
        - Performance issues
    validations:
      required: true

  - type: textarea
    id: command-used
    attributes:
      label: AI Command Used
      description: The exact AI command that caused the issue
      placeholder: |
        ```bash
        # Example commands
        npm run dev -- ai ask "Explain TypeScript interfaces"
        npm run dev -- ai analyze src/index.ts --type security
        npm run dev -- ai generate --language typescript
        npm run dev -- ai chat
        npm run dev -- ai stats
        ```
      render: shell
    validations:
      required: true

  - type: textarea
    id: error-logs
    attributes:
      label: Error Logs
      description: AI-related error logs and output
      placeholder: |
        ```
        [Paste AI error logs here]
        - Anthropic SDK errors
        - Network errors
        - Authentication errors
        - Rate limiting messages
        - Timeout errors
        ```
      render: shell

  - type: dropdown
    id: api-key-setup
    attributes:
      label: API Key Setup
      description: How is your Anthropic API key configured?
      options:
        - Environment variable (ANTHROPIC_API_KEY)
        - .env file
        - Command line parameter
        - Configuration file
        - Not configured (testing without key)
        - Other method
    validations:
      required: true

  - type: dropdown
    id: model-used
    attributes:
      label: Claude Model
      description: Which Claude model were you trying to use?
      options:
        - claude-3-haiku-20240307 (default)
        - claude-3-sonnet-20240229
        - claude-3-opus-20240229
        - claude-3-5-sonnet-20241022
        - claude-3-5-haiku-20241022
        - Auto-selected
        - Custom model
        - Don't know

  - type: textarea
    id: ai-configuration
    attributes:
      label: AI Configuration
      description: Your AI-related configuration
      placeholder: |
        ```bash
        # Environment variables
        CES_ANTHROPIC_MODEL=claude-3-haiku-20240307
        CES_ANTHROPIC_MAX_TOKENS=2048
        CES_ANTHROPIC_TEMPERATURE=0.7
        CES_ANTHROPIC_TIMEOUT=30000
        CES_ANTHROPIC_MAX_RETRIES=2
        
        # Configuration from: npm run dev -- config show --section=anthropic
        ```
      render: shell

  - type: dropdown
    id: network-environment
    attributes:
      label: Network Environment
      description: What network environment are you using?
      options:
        - Direct internet connection
        - Corporate proxy
        - VPN connection
        - Restricted network
        - Offline/air-gapped
        - Other

  - type: textarea
    id: system-info
    attributes:
      label: System Information
      description: System information relevant to AI integration
      value: |
        - OS: [e.g. Ubuntu 22.04, macOS 13, Windows 11]
        - Node.js Version: [e.g. 20.10.0]
        - npm Version: [e.g. 10.2.3]
        - Network connectivity: [online/offline/proxy]
        - Firewall settings: [relevant restrictions]
        - Corporate environment: [yes/no]
    validations:
      required: true

  - type: textarea
    id: usage-context
    attributes:
      label: Usage Context
      description: In what context were you using the AI features?
      placeholder: |
        - What task were you trying to accomplish?
        - How frequently do you use AI features?
        - Is this a recurring issue or one-time?
        - What was the size/complexity of your request?
        - Were you using streaming or regular responses?

  - type: textarea
    id: workarounds
    attributes:
      label: Workarounds Found
      description: Any workarounds you've discovered
      placeholder: |
        - Alternative commands that work
        - Configuration changes that help
        - Different models that work better
        - Manual steps to achieve the goal

  - type: checkboxes
    id: troubleshooting
    attributes:
      label: Troubleshooting Done
      description: What troubleshooting steps have you already tried?
      options:
        - label: Verified API key is correctly set
        - label: Tested with different models
        - label: Checked network connectivity
        - label: Reviewed error logs
        - label: Tried with minimal configuration
        - label: Tested with different command parameters
        - label: Checked CES documentation
        - label: Verified Anthropic SDK version compatibility

  - type: textarea
    id: feature-request
    attributes:
      label: Related Feature Request
      description: If this reveals missing functionality, describe what would help
      placeholder: |
        - Better error messages
        - Additional configuration options
        - Different model options
        - Improved documentation
        - Additional AI commands

  - type: checkboxes
    id: privacy-consent
    attributes:
      label: Privacy & Data Consent
      description: AI integration data handling consent
      options:
        - label: I understand that API calls to Anthropic may include my prompts/data
          required: true
        - label: I have reviewed sensitive data before including in this report
          required: true
        - label: I consent to sharing necessary technical details for debugging
          required: true