name: 🐛 Bug Report
description: Report a bug or issue with Claude Ecosystem Standard
title: "[BUG] "
labels: ["bug", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

  - type: input
    id: version
    attributes:
      label: CES Version
      description: What version of Claude Ecosystem Standard are you using?
      placeholder: v2.7.0
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: In which environment did this bug occur?
      options:
        - Development
        - Staging
        - Production
        - Docker Container
        - Local Installation
        - Kubernetes Cluster
        - CI/CD Pipeline
        - Integration Mode
        - Standalone Mode
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run command '...'
        2. Navigate to '...'
        3. Click on '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened.
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: If applicable, add error logs or screenshots to help explain your problem.
      render: shell

  - type: textarea
    id: system
    attributes:
      label: System Information
      description: Please provide your system information
      value: |
        - OS: [e.g. Ubuntu 22.04, macOS 13, Windows 11]
        - Node.js Version: [e.g. 20.10.0]
        - npm Version: [e.g. 10.2.3]
        - CES Installation Type: [e.g. npm, Docker, source]
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have provided all required information above
          required: true
        - label: I have tested this with the latest version of CES
          required: false