name: ✨ Feature Request
description: Suggest a new feature or enhancement for Claude Ecosystem Standard
title: "[FEATURE] "
labels: ["enhancement", "feature-request"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please provide detailed information about your request.

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What category does this feature belong to?
      options:
        - CLI Commands
        - Session Management
        - Analytics & Monitoring
        - AI Integration
        - Anthropic SDK
        - AI Session Optimization
        - Configuration
        - Security
        - Performance
        - Documentation
        - Developer Experience
        - Cloud Integration
        - Auto-Recovery
        - Enterprise Features
        - Other
    validations:
      required: true

  - type: input
    id: title
    attributes:
      label: Feature Title
      description: A concise title for the feature
      placeholder: e.g. "Add real-time session monitoring dashboard"
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What's the current limitation?
      placeholder: Currently, users cannot... which makes it difficult to...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented
      placeholder: I would like to see...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: I also considered...

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve workflow
        - High - Blocking current work
        - Critical - Essential for adoption
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: Expected Complexity
      description: How complex do you think this feature would be to implement?
      options:
        - Low - Simple configuration or UI change
        - Medium - New feature with moderate implementation
        - High - Complex feature requiring significant changes
        - Unknown - Not sure about implementation complexity

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Describe specific use cases or scenarios where this feature would be valuable
      placeholder: |
        1. When working on large projects...
        2. During team collaboration...
        3. For production deployments...

  - type: textarea
    id: mockups
    attributes:
      label: Mockups or Examples
      description: If applicable, provide mockups, examples, or references from other tools
      placeholder: |
        ```bash
        # Example command usage
        npm run ces -- new-feature --option value
        ```

  - type: checkboxes
    id: requirements
    attributes:
      label: Requirements
      description: What requirements should this feature meet?
      options:
        - label: Should work across all supported platforms (Windows, macOS, Linux)
        - label: Should maintain backward compatibility
        - label: Should include comprehensive documentation
        - label: Should include automated tests
        - label: Should follow existing CLI patterns
        - label: Should integrate with existing session management
        - label: Should support enterprise environments

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: What would make this feature complete and acceptable?
      placeholder: |
        - [ ] Feature works as described
        - [ ] Documentation is updated
        - [ ] Tests are included
        - [ ] No breaking changes

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have provided sufficient detail for the development team to understand the request
          required: true
        - label: This feature aligns with the goals of Claude Ecosystem Standard
          required: true