name: 🚀 Performance Issue
description: Report a performance problem with Claude Ecosystem Standard
title: "[PERFORMANCE] "
labels: ["performance", "optimization", "medium-priority"]
assignees:
  - performance-engineer

body:
  - type: markdown
    attributes:
      value: |
        ## 🚀 Performance Issue Report
        
        Help us improve CES performance by providing detailed information about performance problems you've encountered.

  - type: input
    id: version
    attributes:
      label: CES Version
      description: What version of Claude Ecosystem Standard are you using?
      placeholder: v2.7.0
    validations:
      required: true

  - type: dropdown
    id: performance-area
    attributes:
      label: Performance Area
      description: Which area is experiencing performance issues?
      options:
        - CLI Command Execution
        - Session Startup/Shutdown
        - Anthropic API Calls
        - Analytics Processing
        - Dashboard Rendering
        - Auto-Recovery Operations
        - File System Operations
        - Memory Usage
        - CPU Utilization
        - Network Operations
        - Database Queries
        - Build Process
        - Test Execution
        - Container Operations
        - Other
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Performance Impact
      description: How severe is the performance impact?
      options:
        - Critical - System unusable
        - High - Significant slowdown affecting productivity
        - Medium - Noticeable delay but workable
        - Low - Minor optimization opportunity
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Performance Issue Description
      description: Detailed description of the performance problem
      placeholder: |
        Describe the performance issue:
        - What operation is slow?
        - How long does it take vs expected time?
        - When did you first notice this?
        - Is it consistent or intermittent?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: How to reproduce this performance issue
      placeholder: |
        1. Start CES with configuration...
        2. Execute command...
        3. Measure time with...
        4. Observe slowness...
    validations:
      required: true

  - type: textarea
    id: expected-performance
    attributes:
      label: Expected Performance
      description: What performance did you expect?
      placeholder: |
        - Expected execution time
        - Expected resource usage
        - Comparison with previous versions
        - Benchmark expectations
    validations:
      required: true

  - type: textarea
    id: actual-performance
    attributes:
      label: Actual Performance
      description: What performance are you experiencing?
      placeholder: |
        - Actual execution time
        - Resource usage observed
        - Performance metrics
        - Screenshots of monitoring tools
    validations:
      required: true

  - type: textarea
    id: performance-metrics
    attributes:
      label: Performance Metrics
      description: Provide specific performance measurements
      placeholder: |
        ```
        # Example metrics
        Command: npm run dev -- start-session
        Time: 15.2 seconds (expected: < 5 seconds)
        CPU: 85% peak usage
        Memory: 512MB peak usage
        Network: 2.3MB transferred
        
        # System monitoring output
        top, htop, or Task Manager output
        ```
      render: shell

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: In which environment is this occurring?
      options:
        - Development
        - Staging
        - Production
        - Docker Container
        - Kubernetes Cluster
        - Local Installation
        - CI/CD Pipeline
        - Integration Mode
        - Standalone Mode
    validations:
      required: true

  - type: textarea
    id: system-specs
    attributes:
      label: System Specifications
      description: Detailed system specifications
      value: |
        - OS: [e.g. Ubuntu 22.04, macOS 13, Windows 11]
        - CPU: [e.g. Intel i7-9750H, Apple M2, AMD Ryzen 7]
        - RAM: [e.g. 16GB, 32GB]
        - Storage: [e.g. SSD, NVMe, HDD]
        - Node.js Version: [e.g. 20.10.0]
        - Available Memory: [free -h output on Linux]
        - Docker Version: [if applicable]
        - Container Resources: [if applicable]
    validations:
      required: true

  - type: textarea
    id: configuration
    attributes:
      label: CES Configuration
      description: Relevant CES configuration details
      placeholder: |
        - CES_OPERATION_MODE: [standalone/integrated]
        - CES_ANALYTICS_ENABLED: [true/false]
        - CES_AI_SESSION_ENABLED: [true/false]
        - Number of MCP servers: [default 14]
        - Custom configuration options
        - Environment variables set
      render: shell

  - type: textarea
    id: profiling-data
    attributes:
      label: Profiling Data
      description: Any profiling or debugging data you've collected
      placeholder: |
        - Node.js profiler output
        - Chrome DevTools performance profiles
        - Memory heap snapshots
        - CPU flame graphs
        - Network timing data
        - Database query logs
        
        Please attach files or provide links to profiling data.

  - type: textarea
    id: workarounds
    attributes:
      label: Workarounds
      description: Have you found any workarounds for this performance issue?
      placeholder: |
        - Configuration changes that help
        - Alternative commands that work better
        - System optimizations applied
        - Reduced functionality that improves performance

  - type: dropdown
    id: data-size
    attributes:
      label: Data Size
      description: How much data is being processed?
      options:
        - Small (< 1MB)
        - Medium (1MB - 100MB)
        - Large (100MB - 1GB)
        - Very Large (> 1GB)
        - Variable
        - Not applicable

  - type: dropdown
    id: concurrency
    attributes:
      label: Concurrency
      description: How many concurrent operations?
      options:
        - Single operation
        - Few concurrent (2-5)
        - Many concurrent (6-20)
        - High concurrency (20+)
        - Variable load
        - Not applicable

  - type: textarea
    id: comparison
    attributes:
      label: Performance Comparison
      description: How does this compare to other tools or previous versions?
      placeholder: |
        - Previous CES version performance
        - Comparison with similar tools
        - Baseline measurements
        - Performance regression analysis

  - type: checkboxes
    id: investigation
    attributes:
      label: Investigation Checklist
      description: What investigation have you done?
      options:
        - label: Tested with minimal configuration
        - label: Verified system resources are available
        - label: Checked for concurrent processes affecting performance
        - label: Tested with different data sizes
        - label: Compared with previous versions
        - label: Collected performance metrics
        - label: Reviewed logs for errors or warnings

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context that might be relevant
      placeholder: |
        - Network conditions
        - Time of day patterns
        - Load patterns
        - External dependencies
        - Recent system changes
        - Other performance issues observed