name: 🛡️ Security Issue
description: Report a security vulnerability in Claude Ecosystem Standard
title: "[SECURITY] "
labels: ["security", "vulnerability", "high-priority"]
assignees:
  - security-lead

body:
  - type: markdown
    attributes:
      value: |
        ## ⚠️ Security Issue Report
        
        **IMPORTANT**: If this is a critical security vulnerability, please follow our responsible disclosure process:
        1. **DO NOT** create a public issue
        2. Email security@anthropic.com with details
        3. Allow 48 hours for initial response
        
        For non-critical security issues, you can continue with this form.

  - type: checkboxes
    id: severity-acknowledgment
    attributes:
      label: Severity Assessment
      description: Please indicate the severity level
      options:
        - label: "🔴 CRITICAL - Immediate threat to production systems"
        - label: "🟠 HIGH - Significant security risk"
        - label: "🟡 MEDIUM - Moderate security concern"
        - label: "🟢 LOW - Minor security improvement"

  - type: input
    id: version
    attributes:
      label: CES Version
      description: What version of Claude Ecosystem Standard is affected?
      placeholder: v2.7.0
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Affected Component
      description: Which component is affected by this security issue?
      options:
        - Anthropic SDK Integration
        - Session Management
        - Authentication/Authorization
        - API Key Handling
        - Configuration Management
        - CLI Interface
        - Analytics System
        - Auto-Recovery System
        - Cloud Integration
        - Docker Container
        - CI/CD Pipeline
        - Dependencies
        - Other
    validations:
      required: true

  - type: dropdown
    id: vulnerability-type
    attributes:
      label: Vulnerability Type
      description: What type of security vulnerability is this?
      options:
        - API Key Exposure
        - Code Injection
        - Path Traversal
        - Unauthorized Access
        - Data Leakage
        - Privilege Escalation
        - Denial of Service
        - Cross-Site Scripting (XSS)
        - SQL Injection
        - Insecure Dependencies
        - Configuration Security
        - Container Security
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Security Issue Description
      description: Detailed description of the security vulnerability
      placeholder: |
        Provide a clear and detailed description of the security issue:
        - What is the vulnerability?
        - How can it be exploited?
        - What is the potential impact?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: How to reproduce this security vulnerability
      placeholder: |
        1. Configure CES with...
        2. Execute command...
        3. Observe vulnerability...
      render: shell
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Security Impact
      description: What is the potential impact of this vulnerability?
      placeholder: |
        - Data that could be exposed
        - Systems that could be compromised
        - User accounts affected
        - Potential for lateral movement
    validations:
      required: true

  - type: textarea
    id: attack-vector
    attributes:
      label: Attack Vector
      description: How could an attacker exploit this vulnerability?
      placeholder: |
        - Required access level
        - Attack complexity
        - User interaction required
        - Network access requirements

  - type: textarea
    id: proof-of-concept
    attributes:
      label: Proof of Concept
      description: Proof of concept code or commands (if safe to share)
      placeholder: |
        ```bash
        # Example commands or code demonstrating the vulnerability
        # Please sanitize any sensitive information
        ```
      render: shell

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: In which environment was this discovered?
      options:
        - Development
        - Staging
        - Production
        - Docker Container
        - Kubernetes
        - CI/CD Pipeline
        - Local Installation
    validations:
      required: true

  - type: textarea
    id: system-info
    attributes:
      label: System Information
      description: Relevant system information
      value: |
        - OS: [e.g. Ubuntu 22.04, macOS 13, Windows 11]
        - Node.js Version: [e.g. 20.10.0]
        - Docker Version: [if applicable]
        - CES Installation Type: [npm, Docker, source]
        - Network Environment: [isolated, corporate, public]
    validations:
      required: true

  - type: textarea
    id: mitigation
    attributes:
      label: Suggested Mitigation
      description: Any suggestions for fixing or mitigating this vulnerability
      placeholder: |
        - Immediate workarounds
        - Long-term fixes
        - Configuration changes
        - Code modifications

  - type: textarea
    id: references
    attributes:
      label: References
      description: Any relevant security references, CVEs, or documentation
      placeholder: |
        - CVE numbers
        - Security advisories
        - Related vulnerabilities
        - Documentation links

  - type: checkboxes
    id: security-checklist
    attributes:
      label: Security Checklist
      options:
        - label: I have verified this is a legitimate security issue
          required: true
        - label: I have not disclosed this publicly before reporting
          required: true
        - label: I have provided sufficient detail for reproduction
          required: true
        - label: I understand this will be handled with appropriate confidentiality
          required: true
        - label: I have checked this is not a duplicate of existing security issues
          required: true

  - type: textarea
    id: contact
    attributes:
      label: Contact Information
      description: How can we contact you for follow-up? (Optional but recommended)
      placeholder: |
        - Email: [your-email@domain.com]
        - Preferred communication method
        - Timezone for coordination
        
        Note: This information will be kept confidential