name: ✅ Basic Check

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: ✅ Repository check
        run: |
          echo "Repository checked successfully"
          echo "Files in src directory:"
          ls -la src/
          echo "Node version:"
          node --version
